from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

from backend.app.config import settings


ProviderName = Literal["mock", "openai_responses", "openai_compatible", "ollama", "huggingface"]


@dataclass(frozen=True)
class ModelMessage:
    role: Literal["user", "assistant", "system"]
    content: str


@dataclass(frozen=True)
class ModelRequest:
    instructions: str
    messages: list[ModelMessage]
    provider: str | None = None
    model: str | None = None
    api_key: str | None = None
    base_url: str | None = None
    temperature: float | None = None


@dataclass(frozen=True)
class ModelResponse:
    text: str
    provider: str
    model: str
    raw: dict[str, Any] = field(default_factory=dict)


class ModelProviderError(RuntimeError):
    pass


def _load_httpx() -> Any:
    try:
        import httpx
    except ImportError as exc:
        raise ModelProviderError(
            "The httpx package is not installed. Install the backend dependencies first."
        ) from exc
    return httpx


def _message_payload(messages: list[ModelMessage]) -> list[dict[str, str]]:
    return [{"role": message.role, "content": message.content} for message in messages]


def _extract_openai_text(payload: dict[str, Any]) -> str:
    top_level = payload.get("output_text")
    if isinstance(top_level, str) and top_level.strip():
        return top_level.strip()

    chunks: list[str] = []
    for item in payload.get("output", []):
        if not isinstance(item, dict) or item.get("type") != "message":
            continue
        for content_item in item.get("content", []):
            if not isinstance(content_item, dict):
                continue
            text = content_item.get("text")
            if isinstance(text, str) and text.strip():
                chunks.append(text.strip())
    return "\n\n".join(chunks).strip()


def _extract_chat_text(payload: dict[str, Any]) -> str:
    choices = payload.get("choices")
    if not isinstance(choices, list) or not choices:
        return ""
    message = choices[0].get("message") if isinstance(choices[0], dict) else None
    if not isinstance(message, dict):
        return ""
    content = message.get("content")
    return content.strip() if isinstance(content, str) else ""


def _extract_error(payload: Any, fallback: str) -> str:
    if isinstance(payload, dict):
        error = payload.get("error")
        if isinstance(error, dict):
            message = error.get("message")
            if isinstance(message, str) and message.strip():
                return message.strip()
        detail = payload.get("detail")
        if isinstance(detail, str) and detail.strip():
            return detail.strip()
    return fallback


def _mock_response(request: ModelRequest, provider: str, model: str) -> ModelResponse:
    if "campaign setup guide" in request.instructions:
        text = (
            "{"
            '"assistant_reply":"I can shape this into a campaign draft. I still need the setting, genre or vibe, and player character concept before bootstrapping.",'
            '"draft":{"allow_inference":true,"player_character":{}},'
            '"ready_to_bootstrap":false,'
            '"missing_fields":["setting_or_lore","genre_vibe","player_character.concept"]'
            "}"
        )
        return ModelResponse(text=text, provider=provider, model=model, raw={"mock": True})
    if "reviewing a" in request.instructions and "campaign session" in request.instructions:
        text = (
            "{"
            '"assistant_summary":"Mock review completed. No continuity findings were generated by the mock provider.",'
            '"findings":[]'
            "}"
        )
        return ModelResponse(text=text, provider=provider, model=model, raw={"mock": True})
    if "annotating a transcript section" in request.instructions:
        text = (
            "{"
            '"summary":"Mock transcript section summary.",'
            '"keywords":["mock"],'
            '"named_entities":[],'
            '"relationship_tags":[],'
            '"scene_tags":[],'
            '"notable_moments":["Mock metadata enrichment was used."]'
            "}"
        )
        return ModelResponse(text=text, provider=provider, model=model, raw={"mock": True})

    user_messages = [message.content.strip() for message in request.messages if message.role == "user"]
    last_user = user_messages[-1] if user_messages else "the scene"
    excerpt = " ".join(last_user.split())[:160]
    text = (
        "_The moment holds for a beat while the scene adjusts around your choice._\n\n"
        f"Mock GM response to: {excerpt}"
    )
    return ModelResponse(text=text, provider=provider, model=model, raw={"mock": True})


def _openai_responses(request: ModelRequest, provider: str, model: str) -> ModelResponse:
    api_key = request.api_key or settings.openai_api_key
    if not api_key:
        raise ModelProviderError(
            "OpenAI API key is not configured. Set CHARACTERRPG_OPENAI_API_KEY or OPENAI_API_KEY."
        )
    base_url = (request.base_url or settings.openai_base_url).rstrip("/")
    httpx = _load_httpx()
    body: dict[str, Any] = {
        "model": model,
        "instructions": request.instructions,
        "input": _message_payload(request.messages),
    }
    if request.temperature is not None:
        body["temperature"] = request.temperature
    with httpx.Client(timeout=60.0) as client:
        response = client.post(
            f"{base_url}/responses",
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            },
            json=body,
        )
    payload = response.json()
    if response.status_code >= 400:
        raise ModelProviderError(_extract_error(payload, f"OpenAI request failed: {response.status_code}"))
    text = _extract_openai_text(payload)
    if not text:
        raise ModelProviderError("OpenAI returned an empty response.")
    return ModelResponse(text=text, provider=provider, model=model, raw=payload)


def _openai_compatible(request: ModelRequest, provider: str, model: str) -> ModelResponse:
    api_key = request.api_key or settings.openai_compatible_api_key or settings.openai_api_key
    base_url = (request.base_url or settings.openai_compatible_base_url or settings.openai_base_url).rstrip("/")
    if not api_key:
        raise ModelProviderError(
            "OpenAI-compatible API key is not configured. Set CHARACTERRPG_OPENAI_COMPATIBLE_API_KEY."
        )
    if not base_url:
        raise ModelProviderError(
            "OpenAI-compatible base URL is not configured. Set CHARACTERRPG_OPENAI_COMPATIBLE_BASE_URL."
        )
    httpx = _load_httpx()
    body: dict[str, Any] = {
        "model": model,
        "messages": [
            {"role": "system", "content": request.instructions},
            *_message_payload(request.messages),
        ],
    }
    if request.temperature is not None:
        body["temperature"] = request.temperature
    with httpx.Client(timeout=60.0) as client:
        response = client.post(
            f"{base_url}/chat/completions",
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            },
            json=body,
        )
    payload = response.json()
    if response.status_code >= 400:
        raise ModelProviderError(
            _extract_error(payload, f"OpenAI-compatible request failed: {response.status_code}")
        )
    text = _extract_chat_text(payload)
    if not text:
        raise ModelProviderError("OpenAI-compatible provider returned an empty response.")
    return ModelResponse(text=text, provider=provider, model=model, raw=payload)


def _ollama(request: ModelRequest, provider: str, model: str) -> ModelResponse:
    base_url = (request.base_url or settings.ollama_base_url).rstrip("/")
    httpx = _load_httpx()
    conversation = "\n".join(
        f"{message.role.upper()}: {message.content}" for message in request.messages
    )
    prompt = f"{request.instructions}\n\n{conversation}".strip()
    body: dict[str, Any] = {
        "model": model,
        "prompt": prompt,
        "stream": False,
    }
    if request.temperature is not None:
        body["options"] = {"temperature": request.temperature}
    with httpx.Client(timeout=120.0) as client:
        response = client.post(f"{base_url}/api/generate", json=body)
    payload = response.json()
    if response.status_code >= 400:
        raise ModelProviderError(_extract_error(payload, f"Ollama request failed: {response.status_code}"))
    text = payload.get("response")
    if not isinstance(text, str) or not text.strip():
        raise ModelProviderError("Ollama returned an empty response.")
    return ModelResponse(text=text.strip(), provider=provider, model=model, raw=payload)


def _huggingface(request: ModelRequest, provider: str, model: str) -> ModelResponse:
    api_key = request.api_key or settings.huggingface_api_key
    base_url = (request.base_url or settings.huggingface_base_url or "").rstrip("/")
    if not api_key:
        raise ModelProviderError(
            "Hugging Face API key is not configured. Set CHARACTERRPG_HUGGINGFACE_API_KEY or HF_TOKEN."
        )
    if not base_url:
        raise ModelProviderError(
            "Hugging Face base URL is not configured. Set CHARACTERRPG_HUGGINGFACE_BASE_URL to an inference endpoint."
        )
    httpx = _load_httpx()
    conversation = "\n".join(
        f"{message.role.upper()}: {message.content}" for message in request.messages
    )
    body = {
        "inputs": f"{request.instructions}\n\n{conversation}".strip(),
        "parameters": {"return_full_text": False},
    }
    with httpx.Client(timeout=120.0) as client:
        response = client.post(
            base_url,
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            },
            json=body,
        )
    payload = response.json()
    if response.status_code >= 400:
        raise ModelProviderError(
            _extract_error(payload, f"Hugging Face request failed: {response.status_code}")
        )
    text = ""
    if isinstance(payload, list) and payload and isinstance(payload[0], dict):
        generated = payload[0].get("generated_text")
        if isinstance(generated, str):
            text = generated.strip()
    elif isinstance(payload, dict):
        generated = payload.get("generated_text")
        if isinstance(generated, str):
            text = generated.strip()
    if not text:
        raise ModelProviderError("Hugging Face endpoint returned an empty response.")
    return ModelResponse(text=text, provider=provider, model=model, raw={"payload": payload})


def generate_model_text(request: ModelRequest) -> ModelResponse:
    provider = (request.provider or settings.default_provider or "mock").strip().lower()
    if provider == "openai":
        provider = "openai_responses"
    model = request.model or _default_model_for(provider)
    if provider == "mock":
        return _mock_response(request, provider, model)
    if provider == "openai_responses":
        return _openai_responses(request, provider, model)
    if provider == "openai_compatible":
        return _openai_compatible(request, provider, model)
    if provider == "ollama":
        return _ollama(request, provider, model)
    if provider == "huggingface":
        return _huggingface(request, provider, model)
    raise ModelProviderError(
        f"Unknown provider {provider!r}. Use mock, openai_responses, openai_compatible, ollama, or huggingface."
    )


def _default_model_for(provider: str) -> str:
    if provider == "ollama":
        return settings.ollama_model
    if provider == "mock":
        return "mock-rpg-model"
    return settings.default_model
